### ISSUE TITLE
Cannot start in python 3.5 and django 1.8.13

### ISSUE THREAD

**Issue by paurullan** [someshchaturvedi/django_profiler#1]
I followed the README and could not make it run. This is python 3.5 and django 1.8.13.

What other info would you need to debug this?

```bash
System check identified no issues (0 silenced).
June 30, 2017 - 12:48:13
Django version 1.8.13, using settings 'main.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
TypeError: __init__() missing 1 required positional argument: 'get_response'
[30/Jun/2017 12:48:36] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
TypeError: __init__() missing 1 required positional argument: 'get_response'
```

**Comment by 0xsomesh** [comment]
Hey paurullan 
Django changed the way it implements middleware after version-1.10. You can read up [here](https://docs.djangoproject.com/en/1.11/topics/http/middleware/) .
This middleware supports django version 1.10 or above. 
I will add this in description. Thanks for pointing out :)
