### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'get_response'

### ISSUE THREAD

**Issue by pawelzny** [someshchaturvedi/django_profiler#2]
I've tried to run your profiler with Python 3.6.1 and django 1.11.3, but I've got exception when Django attempt to create instance of profiler middleware class without any arguments.

I follow installation guide. Profiler middleware is last on the list, debug and profiler activation is set to True.

Traceback below:

```shell
System check identified no issues (0 silenced).
July 06, 2017 - 19:35:23
Django version 1.11.3, using settings 'profiler_test.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f23c817b7b8>
Traceback (most recent call last):
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 147, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 28, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 68, in get_handler
    return get_internal_wsgi_application()
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/pawelzny/projects/profiler_test/profiler_test/wsgi_dev.py", line 18, in <module>
    application = get_wsgi_application()
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/handlers/base.py", line 58, in load_middleware
    mw_instance = mw_class()
TypeError: __init__() missing 1 required positional argument: 'get_response'
```

**Comment by 0xsomesh** [comment]
Try this
```bash
pip uninstall customizable-django-profiler
pip install git+https://github.com/someshchaturvedi/customizable-django-profiler.git
```
I have made some changes.
Let me know if that helps.

**Comment by pawelzny** [comment]
One problem solved, but there is another.
This exception occurred in every view even in Django admin:

```shell
System check identified no issues (0 silenced).
July 07, 2017 - 18:56:53
Django version 1.11.3, using settings 'profiler_test.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/template/base.py", line 205, in render
    with context.bind_template(self):
  File "/usr/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/pawelzny/.virtualenvs/profiler_test/lib/python3.6/site-packages/django/template/context.py", line 263, in bind_template
    updates.update(processor(self.request))
TypeError: 'cProfileMiddleware' object is not iterable
ERROR "GET /admin/ HTTP/1.1" 500 126832
```

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @
